// src/client/pages/PageNotFound/PageNotFound.svelte
<script lang="ts">
    import { Error } from '@/client/Error'
    import { UrlBuilder } from '@/client/routes'
</script>

<Error title="Uh oh!" subtitle="Seems like there's nothing here.">
    <p>The page you&apos;re looking for is not available. Try using the top navigation bar to find cool, awesome content! Or, click the button below to go back to the home page.</p>
    <a class="as-button" href={new UrlBuilder().home()}>Home</a>
</Error>

// src/client/components/pages/PageNotFound/PageNotFound.jsx
import React from 'react';
import Error from 'Client/components/layout/Error';
import Button from 'Client/components/core/Button';
import Link from 'Client/components/core/Link';
import { UrlBuilder } from 'Client/config/links';

import styles from './style';

const PageNotFound = () =>
  <Error title='Uh oh!' subtitle="Seems like there's nothing here.">
    <p className={styles.text}>
      The page you&apos;re looking for is not available. Try using the top navigation bar to find cool, awesome content! Or, click the button below to go back to the home page.
    </p>
    <Button primary tag={Link} to={new UrlBuilder().home()} className={styles.button}>Home</Button>
  </Error>;

export default PageNotFound;
