// src/client/pages/WhodokuPage/WhodokuPage.svelte
<script lang="ts">
    import { DocumentInfo } from '@/client/layout/DocumentInfo'
    import { Container } from '@/client/layout/Container'
    import { UrlBuilder, navigation } from '@/client/routes'
    import { FocusOnMe } from '@/client/FocusOnMe'
</script>

<DocumentInfo title="Whodoku" description="Fun sudoku widget which is actually an inside joke between me and some friends.">
    <Container>
        <FocusOnMe><h1 class="title">Whodoku!</h1></FocusOnMe>
        <p class="instructions">Tap an empty square until it is the face you want!</p>
        <whodoku-widget assetsPath={new UrlBuilder().assets().page(navigation.Whodoku.link).base()}></whodoku-widget>
    </Container>
</DocumentInfo>

<style>
    .title, .instructions {
        text-align: center;
    }

    whodoku-widget {
        margin-bottom: var(--sizing-spacing-xl);
    }
</style>

// src/client/components/pages/WhodokuPage/WhodokuPage.jsx
import React from 'react';
import DocumentTitle from 'Client/components/layout/DocumentTitle';
import Container from 'Client/components/core/Container';
import Whodoku from 'Client/components/widgets/Whodoku';
import PageTitle from 'Client/components/layout/PageTitle';

import styles from './style';

const WhodokuPage = () =>
  <DocumentTitle title='Whodoku'>
    <Container>
      <PageTitle className={styles.title}>Whodoku!</PageTitle>
      <p className={styles.instructions}>Tap an empty square until it is the face you want!</p>
      <Whodoku />
    </Container>
  </DocumentTitle>;

export default WhodokuPage;
