// src/client/components/pages/PostsRouter/PostPage/PostPage.jsx
import React from 'react';
import PropTypes from 'Client/utils/prop-types';
import DocumentTitle from 'Client/components/layout/DocumentTitle';
import PostsStore from 'Client/store/posts-store';
import ResourceStore from 'Client/store/resource-store';
import Loading from 'Client/components/core/Loading';
import ShareButtons from './ShareButtons';
import RelatedPosts from './RelatedPosts';
import DateDisplay from 'Client/components/core/DateDisplay';
import RconRenderer from 'Client/components/core/RconRenderer';
import Comments from './Comments';
import { renderIfElse } from 'Client/utils/render-if';

import Article, {
  Header,
  ButtonBar,
  Body,
  Content,
  Aside
} from 'Client/components/layout/Article';

import styles from './style';

class PostPage extends React.Component {
  componentDidMount() {
    this.props.store.refreshList();
  }

  render() {
    const item = this.props.item;
    const similarPosts = item ? this.props.store.list()
      .filter(PostsStore.filter().without(item.id))
      .filter(PostsStore.filter().withCategory(item.category))
      .sort(PostsStore.sorter().byPublishedDate)
      .filter(PostsStore.filter().top(5)) : [];
    
    return <DocumentTitle title={item.title}>
      <Article>
        <Header title={item.title} color={item.color} icon={item.icon} />
        <ButtonBar>
          <ShareButtons post={item} />
        </ButtonBar>
        <Body>
          <Content>
            {renderIfElse(!item.content && this.props.store.isRefreshing, () =>
              <Loading text='Fetching content...' />
            ).elseRender(() =>
              <React.Fragment>
                <DateDisplay className={styles['minor-title']} date={new Date(item.publishedAt)} />
                <RconRenderer rcon={item.content || []} />
                <Comments slug={item.id} />
              </React.Fragment>
            )}
          </Content>
          <Aside title={`More on ${item.category}`}>
            <RelatedPosts posts={similarPosts} />
          </Aside>
        </Body>
      </Article>
    </DocumentTitle>;
  }
}

PostPage.propTypes = {
  item: PropTypes.post.isRequired,
  store: PropTypes.instanceOf(ResourceStore).isRequired
};

export default PostPage;

// src/client/posts/PostPage/PostPage.svelte
<script lang="ts">
    import { DocumentTitle } from '@/client/DocumentTitle'
    import { Container } from '@/client/Container'
    import { Content } from '@/client/Content'
    import { Loading } from '@/client/Loading'
    import { RawRenderer } from '@/client/RawRenderer'
    import type { Resource, Maybe } from '@/client/resources'
    import { Pending, Missing } from '@/client/resources'
    import { PageNotFound } from '@/client/PageNotFound'

    import type { Post } from '../types'

    import { DateDisplay } from '../DateDisplay'
    import { Header } from './Header'
    import { Comments } from './Comments'
    import { RelatedItems } from './RelatedItems'
    import { LinkBar } from './LinkBar'

    export let id: string
    export let resource: Resource<Post>

    let item: Maybe<Post> = Pending
    let relatedItems: Maybe<Post[]> = Pending
    let title: string = ''
    $: {
        item = resource.one(id)
        if (item !== Pending && item !== Missing) {
            title = item.title
            relatedItems = resource.list()
            if (relatedItems !== Pending && relatedItems !== Missing) {
                relatedItems = relatedItems.filter(i => i.category === (item as Post).category && i.id !== (item as Post).id)
            }
        }
    }
</script>

<DocumentTitle {title}>
    <Container>
        {#if item === Pending}
            <Loading text="Finding post..." large />
        {:else if item === Missing}
            <PageNotFound />
        {:else}
            <article class="article" style={`--article-color: var(--palette-${item.color});`}>
                <Header title={item.title} icon={item.icon} />
                {#if item.links}
                    <LinkBar links={item.links} />
                {/if}
                <Content>
                    <section class="content">
                        <div class="published"><DateDisplay date={item.publishedAt} /></div>
                        {#if item.content}
                            <RawRenderer content={item.content} />
                        {:else}
                            <Loading text="Fetching content..." />
                        {/if}
                    </section>
                    <aside slot="sidebar">
                        <h2 class="more-title">More on {item.category}</h2>
                        {#if relatedItems !== Pending && relatedItems !== Missing}
                            <RelatedItems items={relatedItems} />
                        {:else}
                            <Loading text="Finding posts..." />
                        {/if}
                    </aside>
                    <section slot="after">
                        <Comments id={item.id} />
                    </section>
                </Content>
            </article>
        {/if}
    </Container>
</DocumentTitle>

<style>
    .article {
        --header-height: 16em;
        position: relative;
    }

    .published {
        margin-bottom: var(--sizing-spacing-p);
        font-weight: var(--typography-light);
    }

    @media screen and (min-width: 75rem) {
        .more-title {
            font-weight: var(--typography-light);
            font-size: var(--sizing-font-sm);
            line-height: 1;
            margin-bottom: var(--sizing-spacing-p);
        }
    }
</style>
