// src/client/pages/LegalPage/LegalPage.svelte
<script lang="ts">
    import { DocumentInfo } from '@/client/layout/DocumentInfo'
    import { Container } from '@/client/layout/Container'
    import { Content } from '@/client/layout/Content'
    import { FocusOnMe } from '@/client/FocusOnMe'
</script>

<DocumentInfo title="Legal" description="Website terms and conditions and privacy policy.">
    <Container>
        <Content>
            <FocusOnMe>
                <h1>Terms and Conditions</h1>
            </FocusOnMe>
            <p>All content provided on this site is for informational purposes only. The owner of this site makes no representations as to the accuracy or completeness of any information on this site or found by following any link on this site. The owner will not be liable for any errors or omissions in this information nor for the availability of this information. The owner will not be liable for any losses, injuries, or damages from the display or use of this information. These terms and conditions of use are subject to change at any time and without notice.</p>

            <h1>Privacy Policy</h1>
            <p>We do not share personal information with third-parties nor do we store information we collect about your visit to this blog for use other than to analyze content performance through the use of cookies, which you can turn off at anytime by modifying your internet browser's settings. We are not responsible for the republishing of the content found on this site on other websites or media without our permission. This privacy policy is subject to change without notice.</p>
        </Content>
    </Container>
</DocumentInfo>

<style>
    h1 {
        text-align: center;
    }
</style>

// src/client/components/pages/LegalPage/LegalPage.jsx
import React from 'react';
import DocumentTitle from 'Client/components/layout/DocumentTitle';
import Container from 'Client/components/core/Container';
import ContentArea from 'Client/components/layout/ContentArea';
import PageTitle from 'Client/components/layout/PageTitle';

const LegalPage = () =>
  <DocumentTitle title='Legal'>
    <Container>
      <ContentArea white>
        <PageTitle>Terms and Conditions</PageTitle>
        <p>All content provided on this site is for informational purposes only. The owner of this site makes no representations as to the accuracy or completeness of any information on this site or found by following any link on this site. The owner will not be liable for any errors or omissions in this information nor for the availability of this information. The owner will not be liable for any losses, injuries, or damages from the display or use of this information. These terms and conditions of use are subject to change at any time and without notice.</p>
        <PageTitle>Privacy Policy</PageTitle>
        <p>We do not share personal information with third-parties nor do we store information we collect about your visit to this blog for use other than to analyze content performance through the use of cookies, which you can turn off at anytime by modifying your internet browser&apos;s settings. We are not responsible for the republishing of the content found on this site on other websites or media without our permission. This privacy policy is subject to change without notice.</p>
      </ContentArea>
    </Container>
  </DocumentTitle>;

export default LegalPage;
